<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EstadoDeCuenta.DTOs\EstadoDeCuenta.DTOs.csproj" />
    <ProjectReference Include="..\EstadoDeCuenta.Infrastructure\EstadoDeCuenta.Infrastructure.csproj" />
    <ProjectReference Include="..\EstadoDeCuenta.Services\EstadoDeCuenta.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>
